apiVersion: apps/v1
kind: Deployment
metadata:
  name: platformservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
      - name: platformservice
        image: smcgettrick/platformservice:latest
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: platformservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platformservice
  ports:
    - port: 80
      targetPort: 80
      name: platformservice
      protocol: TCP
